# Generated by Django 3.1.5 on 2021-12-22 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20211221_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade.category', verbose_name='Категория')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade.unit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['title'],
            },
        ),
    ]
