# Generated by Django 3.2.12 on 2022-02-09 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20220110_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomercheck', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomerdoc', models.CharField(max_length=20, verbose_name='Номер документв')),
                ('datadoc', models.DateField(verbose_name='Дата документа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Создан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Обновлен')),
                ('buytotal', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('saletotal', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('transaction', models.BooleanField(default=False, verbose_name='Проведен')),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trade.saler', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='TempCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idgood', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('maxvolume', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Создан')),
            ],
        ),
        migrations.CreateModel(
            name='TypeDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Тип документа')),
            ],
        ),
        migrations.CreateModel(
            name='DocJurnal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('buyprice', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('percent', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('saleprice', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('buytotal', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('saletotal', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Создан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Обновлен')),
                ('typedoc', models.IntegerField(null=True)),
                ('nomercheck', models.IntegerField(blank=True, null=True, verbose_name='Номер чека')),
                ('iddoc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade.doc', verbose_name='Документ')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade.good', verbose_name='Наименование товара')),
            ],
            options={
                'verbose_name': 'Наименование',
                'verbose_name_plural': 'Наименования',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='doc',
            name='typedoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade.typedoc', verbose_name='Тип документа'),
        ),
    ]
