# Generated by Django 3.1.13 on 2022-02-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20220209_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='datadoc',
            field=models.DateField(blank=True, null=True, verbose_name='Дата документа'),
        ),
    ]
