# Generated by Django 3.1.13 on 2022-02-24 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_auto_20220224_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trade.saler', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='typedoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trade.typedoc', verbose_name='Тип документа'),
        ),
    ]
